-- Final schema hardening: Resetting tables to ensure clean 14-stage start
DROP TABLE IF EXISTS TASKS;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS NOTIFICATIONS;
DROP TABLE IF EXISTS DELIVERABLES;
DROP TABLE IF EXISTS PROJECTS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS STAGES;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS PLATFORMS;
DROP TABLE IF EXISTS SYSTEM_SETTINGS;

-- Roles Table
CREATE TABLE IF NOT EXISTS ROLES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

-- Users Table
CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES ROLES(id)
);

-- Audit Logs Table
CREATE TABLE IF NOT EXISTS AUDIT_LOGS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(255) NOT NULL,
    entity VARCHAR(100),
    outcome VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE SET NULL
);

-- Platforms Table
CREATE TABLE IF NOT EXISTS PLATFORMS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    api_type VARCHAR(20),
    aspect_ratio VARCHAR(10),
    max_duration_seconds INT,
    caption_max_length INT
);

-- Stages Table
CREATE TABLE IF NOT EXISTS STAGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    sort_order INT NOT NULL
);

-- Projects Table
CREATE TABLE IF NOT EXISTS PROJECTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (creator_id) REFERENCES USERS(id) ON DELETE CASCADE
);

-- Deliverables Table
CREATE TABLE IF NOT EXISTS DELIVERABLES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    platform_id INT NOT NULL,
    stage_id INT NOT NULL,
    caption TEXT,
    media_url VARCHAR(500),
    scheduled_at TIMESTAMP NULL,
    published_at TIMESTAMP NULL,
    stage_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'PENDING',
    FOREIGN KEY (project_id) REFERENCES PROJECTS(id) ON DELETE CASCADE,
    FOREIGN KEY (platform_id) REFERENCES PLATFORMS(id),
    FOREIGN KEY (stage_id) REFERENCES STAGES(id)
);

-- Comments Table
CREATE TABLE IF NOT EXISTS COMMENTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    deliverable_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    comment_text TEXT NOT NULL,
    decision VARCHAR(20), -- APPROVED, REJECTED, NEUTRAL
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (deliverable_id) REFERENCES DELIVERABLES(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_id) REFERENCES USERS(id)
);

-- Notifications Table
CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    related_deliverable_id BIGINT,
    type VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    FOREIGN KEY (related_deliverable_id) REFERENCES DELIVERABLES(id) ON DELETE SET NULL
);

-- Tasks Table
CREATE TABLE IF NOT EXISTS TASKS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    deliverable_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    is_complete BOOLEAN DEFAULT FALSE,
    priority VARCHAR(20) DEFAULT 'MEDIUM',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (deliverable_id) REFERENCES DELIVERABLES(id) ON DELETE CASCADE
);

-- System Settings Table
CREATE TABLE IF NOT EXISTS SYSTEM_SETTINGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value VARCHAR(255) NOT NULL
);

-- Connected Accounts Table (OAuth 2.0 Vault)
CREATE TABLE IF NOT EXISTS CONNECTED_ACCOUNTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    platform_name VARCHAR(50) NOT NULL,
    access_token TEXT NOT NULL,
    refresh_token TEXT,
    expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    UNIQUE(user_id, platform_name)
);
